syntax = "proto3";

package auth;

option csharp_namespace = "Challenge.Common.Messaging.Grpc";

import "Protos/Auth/create_group.proto";
import "Protos/Auth/disable_user.proto";
import "Protos/Auth/login.proto";
import "Protos/Auth/register_user.proto";

service AuthService {
  rpc CreateGroup(CreateGroupRequest) returns (CreateGroupResponse);
  rpc DisableUser(DisableUserRequest) returns (DisableUserResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc RegisterUser(RegisterUserRequest) returns (RegisterUserResponse);
}
